{{- range $secretName, $secretData := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app: {{ $.Release.Name }}
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "*"
type: Opaque
data:
  {{- range $key, $value := $secretData }}
    {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
