
{{- range $configMapName, $configMapData := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMapName }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "*"
data:
  {{ $configMapData | toYaml | nindent 2 }}
{{- end }}

